trigger:
  pr: [ 'x' ]

pool:
  vmImage: ubuntu-latest

steps:
 - bash: |
      set -euo pipefail
      sudo apt-get update
      sudo apt-get -y install gcc-9 g++-9 cmake openmpi-bin openmpi-common libopenmpi-dev libmetis-dev libparmetis-dev libeigen3-dev python3 python3-numpy libopenblas-base libopenblas-dev liblua5.3-0 liblua5.3-dev

   displayName: 'before_install'

 - bash: |
      wget http://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-lite-3.13.3.tar.gz
      tar -xvf petsc-lite-3.13.3.tar.gz
      cd petsc-3.13.3
      ./configure --with-debugging=0 CC=mpicc CXX=mpicxx --prefix=/usr/local/
      make PETSC_DIR=`pwd` PETSC_ARCH=arch-linux-c-opt -j4
      sudo make PETSC_DIR=`pwd` PETSC_ARCH=arch-linux-c-opt install
      cd ..
   displayName: 'install'
 - bash: |
    mkdir build && cd build
    cmake ..
    make -j2
    make test
   displayName: 'Run a multi-line script'
