pr:
  # Do not run Azure CI for docs-only/example-only changes:
  paths:
    include:
      - '*'
    exclude:
      - docs

pool:
  vmImage: ubuntu-latest

steps:
 - bash: |
      set -euo pipefail
      sudo apt-get update
      sudo apt-get -y install gcc-9 g++-9 cmake openmpi-bin openmpi-common libopenmpi-dev libmetis-dev libparmetis-dev libeigen3-dev python3 python3-numpy libopenblas-base libopenblas-dev liblua5.3-0 liblua5.3-dev

   displayName: 'before_install'

 - bash: |
      set -euo pipefail
      wget http://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-lite-3.14.6.tar.gz
      tar -xvf petsc-lite-3.14.6.tar.gz
      cd petsc-3.14.6
      ./configure --with-fortran-bindings=0 --with-debugging=0 \
          --with-memalign=32 --with-64-bit-indices \
          CC=mpicc CXX=mpicxx FC=mpif90 --prefix=/usr/local/ 
      COPTFLAGS="-g -O3" CXXOPTFLAGS="-g -O3"
      make PETSC_DIR=`pwd` PETSC_ARCH=arch-linux-c-opt -j4
      sudo make PETSC_DIR=`pwd` PETSC_ARCH=arch-linux-c-opt install
      cd ..

   displayName: 'install petsc'
 - bash: |
    set -euo pipefail
    mkdir build && cd build
    cmake ..
    make -j2
    make test
   displayName: 'install and test tandem'
