name: Doc preview

on:
  pull_request:
    branches:
      - 'master'

  push:
    branches:
      - ['master', ' thomas/fix_doc']

  workflow_dispatch:

jobs:

  documentation-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: readthedocs/actions/preview@v1
        with:
          project-slug: "tandem"
